# Generated by Django 3.2.4 on 2021-06-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sahitya',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('decs', models.TextField(default='')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
