# Generated by Django 3.2.4 on 2021-06-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatePost',
            new_name='Post',
        ),
    ]
