# Generated by Django 3.2.4 on 2021-06-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=2, max_length=130),
            preserve_default=False,
        ),
    ]
