# Generated by Django 3.2.4 on 2021-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='decs',
            field=models.TextField(default=''),
        ),
    ]
